### ISSUE TITLE
Won't loading at all

### ISSUE THREAD

**Issue by Faxerlander** [HDest-Community/HDest-Critters#5]
This error I'm constantly getting when I'm trying to load Critters along with the last ver of HDest. No clue how to fix that by myself. I've got an old version with no rats and less withered diversity and it worked, but this version is won't loading at all.
![Снимок экрана 2024-11-05 163157](https://github.com/user-attachments/assets/0e38d98b-329f-4945-8b92-557893666595)

**Comment by UndeadZeratul** [comment]
The latest release of HDest or the latest commit on main?  The errors regarding `A_GibSplatter` are from semi-recent universal gibbing stuff that Matt added, and the override to `ValidTarget` was something I made a PR for, they definitely work on the latest HDest

Actually yeah, you have HDest 4.11.3d.pk7, you'll need the latest commits on the main branch:

![image](https://github.com/user-attachments/assets/37d4b420-20c6-4eef-9a2e-c36822a1be97)
https://codeberg.org/mc776/HideousDestructor
